clip_param: 0.2
device: cuda:0
dist_beta: 0
fov: 3.141592653589793
gae_lambda: 0.95
gamma: 0.99
is_target_gae: 0
kl_margin: 1.4
kl_stop: true
log_dir: output_radar/ppo_agent/20230912_151142
lr_actor: 0.0003
lr_critic: 0.00125
lr_decay: 1
map_len: 24
map_radar: 0
map_side_grids: 224
max_ep_len: 200
max_grad_norm: 0.5
n_epoch: 4000
name: ppo_agent
norm_adv: 1
orth_init: 1
repeat_per_epoch: 8
reward_distance_goal: 1.5
reward_distance_move: 0.05
reward_scaling: 1
reward_weight_collision: -45
reward_weight_goal: 75
reward_weight_move: -0.08
reward_weight_proximity: 20
reward_weight_turning: 0.075
reward_weight_w: 1
sample_points_num: 10
seed: 42
target_kl: 0.01
use_gru: 0
use_rnn: 0
world: C:/webots/corner_nav/worlds/indoor_corner_nav.wbt
